/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'both' : IDL.Null,
  'laserCutting' : IDL.Null,
  'pressBrake' : IDL.Null,
});
export const ContactRequest = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRequestByTimestamp' : IDL.Func([IDL.Int], [ContactRequest], ['query']),
  'getRequestsByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'both' : IDL.Null,
    'laserCutting' : IDL.Null,
    'pressBrake' : IDL.Null,
  });
  const ContactRequest = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimFirstAdmin' : IDL.Func([], [IDL.Bool], []),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRequestByTimestamp' : IDL.Func([IDL.Int], [ContactRequest], ['query']),
    'getRequestsByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
