/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceType = IDL.Variant({
  'both' : IDL.Null,
  'laserCutting' : IDL.Null,
  'pressBrake' : IDL.Null,
});
export const ContactRequest = IDL.Record({
  'serviceType' : ServiceType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
  'getRequestByTimestamp' : IDL.Func([IDL.Int], [ContactRequest], ['query']),
  'getRequestsByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(ContactRequest)],
      ['query'],
    ),
  'submitRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceType = IDL.Variant({
    'both' : IDL.Null,
    'laserCutting' : IDL.Null,
    'pressBrake' : IDL.Null,
  });
  const ContactRequest = IDL.Record({
    'serviceType' : ServiceType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllRequests' : IDL.Func([], [IDL.Vec(ContactRequest)], ['query']),
    'getRequestByTimestamp' : IDL.Func([IDL.Int], [ContactRequest], ['query']),
    'getRequestsByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(ContactRequest)],
        ['query'],
      ),
    'submitRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ServiceType, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };